{
  "steps": [
    {
      "name": "gcr.io/cloud-builders/docker",
      "args": [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/job-automation",
        "."
      ]
    },
    {
      "name": "gcr.io/cloud-builders/docker",
      "args": [
        "push",
        "gcr.io/$PROJECT_ID/job-automation"
      ]
    },
    {
      "name": "gcr.io/cloud-builders/gcloud",
      "args": [
        "run",
        "deploy",
        "job-automation",
        "--image",
        "gcr.io/$PROJECT_ID/job-automation",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--set-env-vars",
        "GMAIL_USER=$_GMAIL_USER,GMAIL_APP_PASSWORD=$_GMAIL_APP_PASSWORD,NOTION_TOKEN=$_NOTION_TOKEN,NOTION_DATABASE_ID=$_NOTION_DATABASE_ID,CV_PRIMARY_URL=$_CV_PRIMARY_URL,OPENAI_API_KEY=$_OPENAI_API_KEY"
      ]
    }
  ],
  "substitutions": {
    "_GMAIL_USER": "",
    "_GMAIL_APP_PASSWORD": "",
    "_NOTION_TOKEN": "",
    "_NOTION_DATABASE_ID": "",
    "_CV_PRIMARY_URL": "",
    "_OPENAI_API_KEY": ""
  }
}